name: Warp
main: at.vailan.warp.Warp
version: '${project.version}'
api-version: '26.2'
description: Allows teleportation to previously configured warp points
author: '${project.author}'

permissions:
  simplewarp.*:
    description: Gives access to all SimpleWarp features
    children:
      simplewarp.use: true
      simplewarp.set: true
      simplewarp.delete: true
      simplewarp.execute: true
    default: op

  simplewarp.admin:
    description: Gives access to all SimpleWarp features
    children:
      simplewarp.use: true
      simplewarp.set: true
      simplewarp.delete: true
      simplewarp.execute: true
    default: op

  simplewarp.use:
    description: Allows using warps
    default: true

  simplewarp.set:
    description: Allows creating warps
    default: op

  simplewarp.delete:
    description: Allows deleting warps
    default: op

  simplewarp.execute:
    description: Allows teleporting other players to warps
    default: op